
spring :
  datasource:
    url: jdbc:mysql://114.71.137.175:56346/kt_spring_security?serverTimezone=UTC&useSSL=false
    username: kitae
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver